export const MODEL_LOAD_ORDER: string[] = [
  "AiApproverPromptVersionV02",
  "AiApproverRunV02",
  "ArtificialIntelligence",
  "Keyword",
  "NewsArticleAggregatorSource",
  "Prompt",
  "State",
  "User",
  "WebsiteDomain",
  "EntityWhoCategorizedArticle",
  "EntityWhoFoundArticle",
  "WeeklyArticleFlowRun",
  "NewsApiRequest",
  "NewsRssRequest",
  "NewsApiRequestWebsiteDomainContract",
  "NewsArticleAggregatorSourceStateContract",
  "Report",
  "Article",
  "ArticleApproved",
  "ArticleContents02",
  "ArticleEntityWhoCategorizedArticleContract",
  "ArticleEntityWhoCategorizedArticleContracts02",
  "ArticleIsRelevant",
  "ArticleKeywordContract",
  "ArticleReportContract",
  "ArticleReviewed",
  "ArticlesApproved02",
  "ArticleStateContract",
  "ArticleStateContract02",
  "AiApproverArticlePredictionV02",
  "ArticleDuplicateAnalysis",
];

export default MODEL_LOAD_ORDER;
